services:
  movement-consumer:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: networkrail-movement-consumer
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./secrets.json:/app/secrets.json:ro
    environment:
      - TZ=Europe/London
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    networks:
      - movement-network
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; print('healthy'); sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  movement-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  logs:
    driver: local
